version: "3"
services:
  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: stock_example
    ports:
      - "3306:3306"
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
